### ISSUE TITLE
Not all sources being displayed

### ISSUE THREAD

**Issue by BSJ64** [Lacro59/playnite-statistics-plugin#12]
Extension doesn't display all sources beyond 14. The ones it picks are very random too. The ones it chooses ones i don't even commonly us. (Not sure why Playnite come up as a source)
![Annotation 2020-07-01 120114](https://user-images.githubusercontent.com/52753199/86271013-306c8f00-bb9a-11ea-9e0a-1eb1c723bfcf.png)
![Annotation 2020-07-01 120115](https://user-images.githubusercontent.com/52753199/86271081-4aa66d00-bb9a-11ea-831b-7b4cdfc2970d.png)

**Comment by Lacro59** [comment]
The Playnite source is the default name for the games added without plateform.
