### ISSUE TITLE
Limit amount of slices in pie chart

### ISSUE THREAD

**Issue by erri120** [Lacro59/playnite-statistics-plugin#13]
Funny things happen when you have a lot of genres: 
![19-07-2020 10-43-41 Statistics](https://user-images.githubusercontent.com/16577545/87871004-70a27e80-c99c-11ea-9703-207de1fe1634.png)

Solution would be to limit the amount of genres, prob using `.Take` on an ordered enumerable with all genres, ordered by amount of games using that genre (descending). Could also just not show genres with only 1 game.

**Comment by Lacro59** [comment]
Oh! It's so beautiful, lol.
